site_name: BU Economics

nav:
    - Home: index.md

    
    
 
    
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - r


markdown_extensions:
  - attr_list
  - md_in_html

